version: '3.8'

services:
  spring-boot-app:
    image: my-spring-boot-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile-spring
    ports:
      - "8086:8080"

  billing-app:
    image: my-spring-boot-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile-spring
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_prometheus &&
             rabbitmq-server"
volumes:
  grafana-data: